server:
  port: 8080
  tomcat:
    threads:
      max: 2
  shutdown: graceful
spring:
  data:
    mongodb:
#      uri: mongodb://mongo-0.mongo/CoderPraBhuApi    
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}/${MONGODB_DB_NAME}?${MONGODB_OPTIONS}
  main:
    banner-mode: "off"
  lifecycle:
    timeout-per-shutdown-phase: 5s
management:
  health:
    probes:
      enabled: true